break resume.json even more to test validation step

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -20,7 +20,7 @@ jobs:
       - id: 'validate'
         # here we validate the json file to have correct syntax
         name: "Validate resume.json"
-        run: python3 -mjson.tool src/resume/resume.json > /dev/null || echo "invalid resume json"      
+        run: python3 -mjson.tool src/resume/resume.json > /dev/null || (echo "Invalid resume json" && exit 1)    
   
       - id: 'auth'
         # here we authenticate with GCP using Service Account
